// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/tpl/add.vue')['default']
    Auth: typeof import('./src/components/modal/auth.vue')['default']
    C1: typeof import('./src/components/modal/c1.vue')['default']
    C2: typeof import('./src/components/modal/c2.vue')['default']
    C3: typeof import('./src/components/modal/c3.vue')['default']
    C4: typeof import('./src/components/modal/c4.vue')['default']
    Close: typeof import('./src/components/tpl/close.vue')['default']
    copy: typeof import('./src/components/modal/c1 copy.vue')['default']
    Create: typeof import('./src/components/tpl/create.vue')['default']
    Edit: typeof import('./src/components/tpl/edit.vue')['default']
    Login: typeof import('./src/components/tpl/login.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sec: typeof import('./src/components/tpl/sec.vue')['default']
    Token: typeof import('./src/components/tpl/token.vue')['default']
    Update: typeof import('./src/components/tpl/update.vue')['default']
  }
}
